flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- async-2.1.1.1
- HTTP-4000.3.7
- StateVar-1.1.0.4
- base-orphans-0.6
- bifunctors-5.4.2
- comonad-5.0.2
- contravariant-1.4
- distributive-0.5.3
- exceptions-0.8.3
- free-4.12.4
- hashable-1.2.6.1
- mtl-2.2.1
- network-2.6.3.2
- network-uri-2.6.1.0
- parsec-3.1.11
- prelude-extras-0.4.0.3
- profunctors-5.2.1
- semigroupoids-5.2.1
- semigroups-0.18.3
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.2
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- void-0.7.2
resolver: ghc-8.0.1
