flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HTTP-4000.3.7
- HUnit-1.6.0.0
- QuickCheck-2.10.0.1
- StateVar-1.1.0.4
- ansi-terminal-0.7.1.1
- async-2.1.1.1
- base-orphans-0.6
- bifunctors-5.4.2
- call-stack-0.1.0
- colour-2.3.3
- comonad-5.0.2
- contravariant-1.4
- distributive-0.5.3
- exceptions-0.8.3
- free-4.12.4
- hashable-1.2.6.1
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- mtl-2.2.1
- network-2.6.3.2
- network-uri-2.6.1.0
- parsec-3.1.11
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2.1
- quickcheck-io-0.2.0
- random-1.1
- semigroupoids-5.2.1
- semigroups-0.18.3
- setenv-0.1.1.3
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.2
- tf-random-0.5
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- void-0.7.2
resolver: ghc-8.0.1
